# https://github.com/natario1/CameraView/blob/master/.github/workflows/build.yml
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Build
on: [push, pull_request]
jobs:
  IOS_SIMULATOR_TESTS:
    name: iOS Simulator Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      - uses: actions/setup-python@v1
      - name: Install idb
        run: |
          brew tap facebook/fb
          brew install idb-companion
          pip install fb-idb
      - run: cp GoogleService-Info.plist.dist ios/GoogleService-Info.plist
      - run: cd ios/ && pod install --repo-update && cd ..
      - run: node node_modules/.bin/detox build -c ios.sim.release
        env:
          googleMapsApiKey: ${{ secrets.googleMapsApiKey }}
      - name: Run Detox tests
        run: node node_modules/.bin/detox test -c ios.sim.release --cleanup --device-name="iPhone 11"
      # See screenshot specifications
      # https://help.apple.com/app-store-connect/#/devd274dd925
      - name: Take screenshots
        if: github.ref == 'refs/heads/master'
        run: |
          node node_modules/.bin/detox test -c ios.sim.release -o e2e/screenshots.config.json --take-screenshots manual --cleanup --device-name="iPhone 11" --artifacts-location ./artifacts/6.5-inch
          node node_modules/.bin/detox test -c ios.sim.release -o e2e/screenshots.config.json --take-screenshots manual --cleanup --device-name="iPhone 8 Plus" --artifacts-location ./artifacts/5.5-inch
          node node_modules/.bin/detox test -c ios.sim.release -o e2e/screenshots.config.json --take-screenshots manual --cleanup --device-name="iPad Pro (12.9-inch) (3rd generation)" --artifacts-location ./artifacts/12.9-inch
      - name: Upload screenshots artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: detox-screenshots-ios
          path: artifacts
  ANDROID_EMULATOR_TESTS:
    name: Android Emulator Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        EMULATOR_API: [28]
        EMULATOR_ARCH: [x86_64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: cp google-services.json.dist android/app/google-services.json
      - name: Enable clear text traffic in release builds
        run: |
          brew install xmlstarlet
          xmlstarlet ed --inplace --ps --insert "/manifest/application" --type attr -n "android:usesCleartextTraffic" -v "true" android/app/src/main/AndroidManifest.xml
      - run: node node_modules/.bin/detox build -c android.emu.release
        env:
          googleMapsApiKey: ${{ secrets.googleMapsApiKey }}
      - name: Execute emulator tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          target: google_apis
          arch: ${{ matrix.EMULATOR_ARCH }}
          profile: Nexus 6
          # https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidEmulatorsBestPractices.md#booting-an-emulator-via-command-line
          emulator-options: -verbose -no-window -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect -camera-back emulated -camera-front emulated
          disable-animations: true
          script: |
            bash -c "echo 'hw.lcd.height=2560' >> /Users/runner/.android/avd/test.avd/config.ini"
            bash -c "echo 'hw.lcd.width=1440' >> /Users/runner/.android/avd/test.avd/config.ini"
            node node_modules/.bin/detox test -c android.att.release --device-name="emulator-5554" --take-screenshots all --loglevel trace
            node node_modules/.bin/detox test -c android.att.release --device-name="emulator-5554" --take-screenshots manual -o e2e/screenshots.config.json --loglevel trace
      - name: Upload screenshots artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: detox-screenshots-android
          path: artifacts
